services:
  website:
    build:
      context: .
      dockerfile: Dockerfile.website
    container_name: biswa-website
    ports:
      - "9900:80"
    restart: unless-stopped

  visualizer:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: biswa-visualizer
    expose:
      - "80"
    restart: unless-stopped
